Ajout quality gate validation cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -112,9 +112,23 @@ jobs:
             -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
             -Dsonar.qualitygate.wait=true
           
+  # Vérification de la Quality Gate de SonarCloud
+  quality-gate:
+    runs-on: ubuntu-latest
+    needs: [backend-tests, frontend-tests]
+    steps:
+      - name: Check SonarCloud Quality Gate
+        run: |
+          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=triny81_bobapp-backend" | jq -r .projectStatus.status)
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality gate failed!"
+            exit 1
+          fi
+
+  # Déploiement des images Docker
   docker-build-push:
     runs-on: ubuntu-latest
-    needs: [backend-tests, frontend-tests]  # Attendre la validation des tests
+    needs: [quality-gate]
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -125,14 +139,15 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Build et push du backend
+      - name: Define Image Tag
+        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
+
       - name: Build and push backend image
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:latest -f back/Dockerfile ./back
-          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:latest
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:${{ env.IMAGE_TAG }} -f back/Dockerfile ./back
+          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:${{ env.IMAGE_TAG }}
 
-      # Build et push du frontend
       - name: Build and push frontend image
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend:latest -f front/Dockerfile ./front
-          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend:latest
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend:${{ env.IMAGE_TAG }} -f front/Dockerfile ./front
+          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend:${{ env.IMAGE_TAG }}
